spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    hikari:
      username: sa
      password:
      driver-class-name: org.h2.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8100

REST_API_KEY: 683a25bcc3f527d02f9db7c483c99196
REDIRECT_URI: http://3.36.247.2/app/kakao/oauth
